/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.SlotMachine;

import BackEnd.DBConnection;
import BackEnd.SlotMachine;
import BackEnd.ImageResizer;
import BackEnd.ManagementClasses.Player;
import GUI.MainPages.HomeScreen;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author Mubashir Ali
 */
public class SlotMachineGUI extends javax.swing.JFrame {

    Player player;

    public SlotMachineGUI(Player player) {
        this.player = player;
        initComponents();
        setPlayerData();
        buttonClear.setVisible(false);
        textMessage.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textMessage = new javax.swing.JLabel();
        buttonClear = new javax.swing.JButton();
        buttonHome = new javax.swing.JButton();
        textUserName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textTokens = new javax.swing.JLabel();
        textSlot2 = new javax.swing.JLabel();
        textPlayerId = new javax.swing.JLabel();
        textSlot1 = new javax.swing.JLabel();
        textSlot = new javax.swing.JLabel();
        btnSpin = new javax.swing.JToggleButton();
        textAvatar = new javax.swing.JLabel();
        textLevel = new javax.swing.JLabel();
        textTotalWins = new javax.swing.JLabel();
        textScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textMessage.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textMessage.setForeground(new java.awt.Color(255, 0, 255));
        jPanel1.add(textMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 470, 30));

        buttonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/RepeatButton.png"))); // NOI18N
        buttonClear.setBorder(null);
        buttonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel1.add(buttonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 80, 80));

        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/HomeBtn.png"))); // NOI18N
        buttonHome.setBorder(null);
        buttonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(buttonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 80, 80));

        textUserName.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        textUserName.setForeground(new java.awt.Color(255, 255, 255));
        textUserName.setText("Name");
        jPanel1.add(textUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 700, -1, -1));

        textTokens.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        textTokens.setForeground(new java.awt.Color(255, 255, 255));
        textTokens.setText("Tokens");
        jPanel1.add(textTokens, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        textSlot2.setFont(new java.awt.Font("Segoe Print", 1, 200)); // NOI18N
        textSlot2.setForeground(new java.awt.Color(255, 0, 255));
        textSlot2.setText("7");
        jPanel1.add(textSlot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 150, 210));

        textPlayerId.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        textPlayerId.setForeground(new java.awt.Color(255, 255, 255));
        textPlayerId.setText("playerid");
        jPanel1.add(textPlayerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        textSlot1.setFont(new java.awt.Font("Segoe Print", 1, 200)); // NOI18N
        textSlot1.setForeground(new java.awt.Color(255, 0, 255));
        textSlot1.setText("7");
        jPanel1.add(textSlot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 150, 210));

        textSlot.setFont(new java.awt.Font("Segoe Print", 1, 200)); // NOI18N
        textSlot.setForeground(new java.awt.Color(255, 0, 255));
        textSlot.setText("7");
        jPanel1.add(textSlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 150, 210));

        btnSpin.setBackground(new java.awt.Color(102, 102, 102));
        btnSpin.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnSpin.setForeground(new java.awt.Color(255, 0, 255));
        btnSpin.setText("Spin with 1 token");
        btnSpin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSpin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpinActionPerformed(evt);
            }
        });
        jPanel1.add(btnSpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 140, 60));

        textAvatar.setText("j");
        textAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255), 2));
        jPanel1.add(textAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 130, 130));

        textLevel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        textLevel.setForeground(new java.awt.Color(255, 255, 255));
        textLevel.setText("Level");
        jPanel1.add(textLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 150, -1));

        textTotalWins.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        textTotalWins.setForeground(new java.awt.Color(255, 255, 255));
        textTotalWins.setText("TotalWins");
        jPanel1.add(textTotalWins, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        textScore.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        textScore.setForeground(new java.awt.Color(255, 255, 255));
        textScore.setText("Scrore");
        jPanel1.add(textScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        clear();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void setPlayerData() {
        textAvatar.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\ArcadeGamingZone\\src\\GUI\\Images\\GamingAvatar.jpg"), textAvatar));
        textPlayerId.setText("Player ID  :     " + player.getPlayerID());
        textUserName.setText("Name       :     " + player.getInGameName());
        textLevel.setText("Level       :     " + player.getLevel());
        textTotalWins.setText("Matchs     :    " + (player.getWins() + player.getLosses()));
        textTokens.setText("Tokens     :     " + player.getNoOfTokens());
        textScore.setText("Score      :     " + player.getScore());
    }

    private void close() {
        WindowEvent windowClose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClose);
    }

    public void clear() {
        buttonClear.setVisible(false);
        btnSpin.setVisible(true);
        textMessage.setText(null);
        printSlots(new int[]{7, 7, 7});

    }

    public void play() {
        btnSpin.setVisible(false);
        buttonClear.setVisible(true);
        SlotMachine sm = new SlotMachine();
        printSlots(sm.getNums());
        update(sm.getPrize());
        player.addScore(sm.getScore());
        player.addTokens(sm.getPrize());
        new DBConnection().UpdateplayerData(player);
        setPlayerData();
    }

    public void printSlots(int[] data) {
        textSlot.setText("" + data[0]);
        textSlot1.setText("" + data[1]);
        textSlot2.setText("" + data[2]);
    }

    public void update(int prize) {
        if (prize == 0) {
            textMessage.setText("Better Luck Next Time!");
            player.addLoss();
        } else {
            textMessage.setText("You Won " + prize + "Tokens. Congrats!");
            player.addWin();
        }
    }


    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        close();
        new HomeScreen(player).setVisible(true);
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void btnSpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpinActionPerformed
       if(player.getNoOfTokens()>0){
           player.takeTokens(1);
           play();
       }else{
           textMessage.setText("out Of tokens please buy some!");
       }
    }//GEN-LAST:event_btnSpinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlotMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlotMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlotMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlotMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlotMachineGUI(new Player("1234", 12, 100, 10, 5, "5210799", "DemonX", 2000, 2, "Mubashir Ali", "mubashiralikalhoro@gmail.com")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSpin;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textAvatar;
    private javax.swing.JLabel textLevel;
    private javax.swing.JLabel textMessage;
    private javax.swing.JLabel textPlayerId;
    private javax.swing.JLabel textScore;
    private javax.swing.JLabel textSlot;
    private javax.swing.JLabel textSlot1;
    private javax.swing.JLabel textSlot2;
    private javax.swing.JLabel textTokens;
    private javax.swing.JLabel textTotalWins;
    private javax.swing.JLabel textUserName;
    // End of variables declaration//GEN-END:variables
}
