package GUI.MainPages;

import BackEnd.DBConnection;
import BackEnd.ImageResizer;
import BackEnd.ManagementClasses.Developer;
import BackEnd.ManagementClasses.Manager;
import BackEnd.ManagementClasses.Player;
import BackEnd.Report;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Mubashir Ali
 */
public class HomeScreenManager extends javax.swing.JFrame {

    private Manager man;

    public HomeScreenManager(Manager man) {
        this.man = man;
        initComponents();
        setData();
        printAllReports();
        printAllPlayers();
    }

    private String printPlayer(Player pl) {
        String re = "";
        re+="\n===========================================";
        re += "\nPlayer ID: " + pl.getPlayerID();
        re += "\nName: " + pl.getUsername();
        re += "\nIn Game Name: " + pl.getInGameName();
        re += "\nEmail: " + pl.getEmail();
        re += "\nLevel: " + pl.getLevel();
        re += "\nScore: " + pl.getScore();
        re += "\nMatchs Player: " + (pl.getWins() + pl.getLosses());
        re += "\nMatchs Won: " + pl.getWins();
        re+="\n===========================================";

        return re;
    }
    
    private void printAllPlayers(){
          String print = "";
     
        for (Player i : new DBConnection().getAllPlayers()) {
            print += printPlayer(i);
            print += "\n\n";
        }
    
        textPlayers.setText(print);
    }
    
    
    
    private String printReport(Report rp) {
        String re = rp.getName() + ":\n\t";
        int temp = 0;
        for (String i : rp.getReport().split(" ")) {
            re += i + " ";
            temp++;
            if (temp > 15) {
                temp = 0;
                re += "\n\t";
            }
        }
        return re;
    }

    private void printAllReports() {
        String print = "";
        for (Report i : new DBConnection().getAllReports()) {
            print += printReport(i);
            print += "\n\n";
        }

        textReports.setText(print);
    }

    private void setData() {
         btnMessage.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\"
                + "ArcadeGamingZone\\src\\GUI\\Images\\messageIcon.jpg"), btnMessage));
        btnLogOut.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\"
                + "ArcadeGamingZone\\src\\GUI\\Images\\logoutIcon.png"), btnLogOut));
        textAvatar.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\"
                + "ArcadeGamingZone\\src\\GUI\\Images\\ManagerAvatar.png"), textAvatar));
        textAssignedWork.setText("Assign work : " + man.getAssignedWork());
        textEmpUsername.setText("Username : " + man.getManName());
        textEmpId.setText("Employee ID : " + man.getEmpID());
        textEmpName.setText("Name : " + man.getUsername());
        textSalary.setText("Salary : " + man.getSalary());
    }

    private void close() {
        WindowEvent windowClose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClose);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textLogOut2 = new javax.swing.JLabel();
        btnMessage = new javax.swing.JButton();
        textLogOut4 = new javax.swing.JLabel();
        textLogOut = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPlayers = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        textReports = new javax.swing.JTextPane();
        textSalary = new javax.swing.JLabel();
        textLogOut1 = new javax.swing.JLabel();
        textLevel = new javax.swing.JLabel();
        textAssignedWork = new javax.swing.JLabel();
        textEmpUsername = new javax.swing.JLabel();
        textEmpName = new javax.swing.JLabel();
        textEmpId = new javax.swing.JLabel();
        textAvatar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textLogOut2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textLogOut2.setForeground(new java.awt.Color(255, 0, 255));
        textLogOut2.setText("Players");
        jPanel1.add(textLogOut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 60, 30));

        btnMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessageActionPerformed(evt);
            }
        });
        jPanel1.add(btnMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 90, 90));

        textLogOut4.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textLogOut4.setForeground(new java.awt.Color(255, 0, 255));
        textLogOut4.setText("Messages");
        jPanel1.add(textLogOut4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 150, 60, 30));

        textLogOut.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textLogOut.setForeground(new java.awt.Color(255, 0, 255));
        textLogOut.setText("Reports");
        jPanel1.add(textLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 60, 30));

        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, 90, 90));

        textPlayers.setBackground(new java.awt.Color(0, 0, 0));
        textPlayers.setForeground(new java.awt.Color(255, 255, 255));
        textPlayers.setText("data");
        textPlayers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textPlayers.setFocusable(false);
        jScrollPane2.setViewportView(textPlayers);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 460, 380));

        textReports.setBackground(new java.awt.Color(0, 0, 0));
        textReports.setForeground(new java.awt.Color(255, 255, 255));
        textReports.setText("data");
        textReports.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textReports.setFocusable(false);
        jScrollPane1.setViewportView(textReports);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 460, 380));

        textSalary.setForeground(new java.awt.Color(255, 255, 255));
        textSalary.setText("salary");
        jPanel1.add(textSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        textLogOut1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textLogOut1.setForeground(new java.awt.Color(255, 0, 255));
        textLogOut1.setText("Log out");
        jPanel1.add(textLogOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 150, 60, 30));

        textLevel.setForeground(new java.awt.Color(255, 255, 255));
        textLevel.setText("Designation : Developer");
        jPanel1.add(textLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 150, -1));

        textAssignedWork.setForeground(new java.awt.Color(255, 255, 255));
        textAssignedWork.setText("assigned work");
        jPanel1.add(textAssignedWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        textEmpUsername.setForeground(new java.awt.Color(255, 255, 255));
        textEmpUsername.setText("username");
        jPanel1.add(textEmpUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        textEmpName.setForeground(new java.awt.Color(255, 255, 255));
        textEmpName.setText("Name");
        jPanel1.add(textEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        textEmpId.setForeground(new java.awt.Color(255, 255, 255));
        textEmpId.setText("empid");
        jPanel1.add(textEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        textAvatar.setText("jLabel2");
        textAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255), 2));
        jPanel1.add(textAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 130, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/homeScreen.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        close();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessageActionPerformed
        close();
        new MessengerGroup(man).setVisible(true);
    }//GEN-LAST:event_btnMessageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreenManager(new Manager("nothing", "@man_mubashir", 100, 1002, "mubashirali@gmail.com", 6, "Mubashir", "mubashirali@gmail.com")).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel textAssignedWork;
    private javax.swing.JLabel textAvatar;
    private javax.swing.JLabel textEmpId;
    private javax.swing.JLabel textEmpName;
    private javax.swing.JLabel textEmpUsername;
    private javax.swing.JLabel textLevel;
    private javax.swing.JLabel textLogOut;
    private javax.swing.JLabel textLogOut1;
    private javax.swing.JLabel textLogOut2;
    private javax.swing.JLabel textLogOut4;
    private javax.swing.JTextPane textPlayers;
    private javax.swing.JTextPane textReports;
    private javax.swing.JLabel textSalary;
    // End of variables declaration//GEN-END:variables
}
