/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.MainPages;

import BackEnd.ImageResizer;
import BackEnd.ManagementClasses.Player;
import GUI.DoubleOrNothing.DoubleOrNothingGUI;
import GUI.RockPaperSessoir.RockPaperSessiorGUI;
import GUI.SlotMachine.SlotMachineGUI;
import GUI.TicTacToe.TicTacToeGUI;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Mubashir Ali
 */
public class HomeScreen extends javax.swing.JFrame {

    private Player player;

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen(Player player) {
        initComponents();
        this.player = player;
        setPlayerData();
        initButtons();
    }

    private void initButtons() {
        btnSellTokens.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\ArcadeGamingZone\\src\\GUI\\Images\\tokens.png"), btnSellTokens));
        btnDoubleOrNothing.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\ArcadeGamingZone\\src\\GUI\\Images\\doubleOrNothingLogoIcon.png"), btnDoubleOrNothing));
        btnLeaderboards.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\ArcadeGamingZone\\src\\GUI\\Images\\leaderBoardIcon.png"), btnLeaderboards));
        btnReport.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\ArcadeGamingZone\\src\\GUI\\Images\\reportIcon.jpg"), btnReport));
        btnLogOut.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\ArcadeGamingZone\\src\\GUI\\Images\\logoutIcon.png"), btnLogOut));
        btnEditProfile.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\ArcadeGamingZone\\src\\GUI\\Images\\editProfieIcon.jpg"), btnEditProfile));
        btnTicTacToe.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\ArcadeGamingZone\\src\\GUI\\Images\\TicTacToe Icon.png"), btnTicTacToe));
        btnRockPaperSessior.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\ArcadeGamingZone\\src\\GUI\\Images\\rockpapersessior icon.png"), btnTicTacToe));
        btnBuyTokens.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\ArcadeGamingZone\\src\\GUI\\Images\\tokens.png"), btnBuyTokens));
        btnSlotMachine.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\ArcadeGamingZone\\src\\GUI\\Images\\slotMachineLogo.jpg"), btnSlotMachine));
    }

    private void setPlayerData() {
        textAvatar.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\ArcadeGamingZone\\src\\GUI\\Images\\GamingAvatar.jpg"), textAvatar));
        textPlayerId.setText("Player ID  :     " + player.getPlayerID());
        textUserName.setText("Name       :     " + player.getInGameName());
        textLevel.setText("Level       :     " + player.getLevel());
        textTotalWins.setText("Matchs     :    " + (player.getWins() + player.getLosses()));
        textTokens.setText("Tokens     :     " + player.getNoOfTokens());
        textScore.setText("Score      :     " + player.getScore());
    }

    HomeScreen() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSellTokens = new javax.swing.JButton();
        textBuyTokens2 = new javax.swing.JLabel();
        btnLeaderboards = new javax.swing.JButton();
        textBuyTokens1 = new javax.swing.JLabel();
        textLogOut = new javax.swing.JLabel();
        textEditProfile1 = new javax.swing.JLabel();
        btnReport = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnEditProfile = new javax.swing.JButton();
        textEditProfile = new javax.swing.JLabel();
        btnSlotMachine = new javax.swing.JButton();
        btnRockPaperSessior = new javax.swing.JButton();
        btnBuyTokens = new javax.swing.JButton();
        btnTicTacToe = new javax.swing.JButton();
        btnDoubleOrNothing = new javax.swing.JButton();
        textTotalWins = new javax.swing.JLabel();
        textBuyTokens = new javax.swing.JLabel();
        textScore = new javax.swing.JLabel();
        textTokens = new javax.swing.JLabel();
        textPlayerId = new javax.swing.JLabel();
        textUserName = new javax.swing.JLabel();
        textLevel = new javax.swing.JLabel();
        textAvatar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSellTokens.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSellTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellTokensActionPerformed(evt);
            }
        });
        jPanel1.add(btnSellTokens, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 90, 90));

        textBuyTokens2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textBuyTokens2.setForeground(new java.awt.Color(255, 0, 255));
        textBuyTokens2.setText("Sell Tokens");
        jPanel1.add(textBuyTokens2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 90, 30));

        btnLeaderboards.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLeaderboards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaderboardsActionPerformed(evt);
            }
        });
        jPanel1.add(btnLeaderboards, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 90, 90));

        textBuyTokens1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textBuyTokens1.setForeground(new java.awt.Color(255, 0, 255));
        textBuyTokens1.setText("LeaderBoards");
        jPanel1.add(textBuyTokens1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 100, 30));

        textLogOut.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textLogOut.setForeground(new java.awt.Color(255, 0, 255));
        textLogOut.setText("Log out");
        jPanel1.add(textLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 150, 60, 30));

        textEditProfile1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textEditProfile1.setForeground(new java.awt.Color(255, 0, 255));
        textEditProfile1.setText("Report");
        jPanel1.add(textEditProfile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, 50, 30));

        btnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        jPanel1.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 90, 90));

        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, 90, 90));

        btnEditProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProfileActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, 90, 90));

        textEditProfile.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textEditProfile.setForeground(new java.awt.Color(255, 0, 255));
        textEditProfile.setText("Edit profile");
        jPanel1.add(textEditProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 80, 30));

        btnSlotMachine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSlotMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlotMachineActionPerformed(evt);
            }
        });
        jPanel1.add(btnSlotMachine, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 110, 110));

        btnRockPaperSessior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRockPaperSessior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRockPaperSessiorActionPerformed(evt);
            }
        });
        jPanel1.add(btnRockPaperSessior, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 110, 110));

        btnBuyTokens.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuyTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyTokensActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuyTokens, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 90, 90));

        btnTicTacToe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTicTacToe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicTacToeActionPerformed(evt);
            }
        });
        jPanel1.add(btnTicTacToe, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 110, 110));

        btnDoubleOrNothing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDoubleOrNothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoubleOrNothingActionPerformed(evt);
            }
        });
        jPanel1.add(btnDoubleOrNothing, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, 110, 110));

        textTotalWins.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        textTotalWins.setForeground(new java.awt.Color(255, 255, 255));
        textTotalWins.setText("TotalWins");
        jPanel1.add(textTotalWins, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        textBuyTokens.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textBuyTokens.setForeground(new java.awt.Color(255, 0, 255));
        textBuyTokens.setText("Buy Tokens");
        jPanel1.add(textBuyTokens, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 90, 30));

        textScore.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        textScore.setForeground(new java.awt.Color(255, 255, 255));
        textScore.setText("Scrore");
        jPanel1.add(textScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        textTokens.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        textTokens.setForeground(new java.awt.Color(255, 255, 255));
        textTokens.setText("Tokens");
        jPanel1.add(textTokens, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        textPlayerId.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        textPlayerId.setForeground(new java.awt.Color(255, 255, 255));
        textPlayerId.setText("playerid");
        jPanel1.add(textPlayerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        textUserName.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        textUserName.setForeground(new java.awt.Color(255, 255, 255));
        textUserName.setText("Name");
        jPanel1.add(textUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        textLevel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        textLevel.setForeground(new java.awt.Color(255, 255, 255));
        textLevel.setText("Level");
        jPanel1.add(textLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 150, -1));

        textAvatar.setText("j");
        textAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255), 2));
        jPanel1.add(textAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 130, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/homeScreen.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close() {
        WindowEvent windowClose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClose);
    }

    private void btnSlotMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlotMachineActionPerformed
        close();
        new SlotMachineGUI(player).setVisible(true);
    }//GEN-LAST:event_btnSlotMachineActionPerformed

    private void btnTicTacToeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicTacToeActionPerformed
        close();
        new TicTacToeGUI(player).setVisible(true);
    }//GEN-LAST:event_btnTicTacToeActionPerformed

    private void btnRockPaperSessiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRockPaperSessiorActionPerformed
        close();
        new RockPaperSessiorGUI(player).setVisible(true);
    }//GEN-LAST:event_btnRockPaperSessiorActionPerformed

    private void btnBuyTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyTokensActionPerformed
        close();
        new BuyMenu(player).setVisible(true);
    }//GEN-LAST:event_btnBuyTokensActionPerformed

    private void btnDoubleOrNothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoubleOrNothingActionPerformed
        close();
        new DoubleOrNothingGUI(player).setVisible(true);
    }//GEN-LAST:event_btnDoubleOrNothingActionPerformed

    private void btnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProfileActionPerformed
        close();
        new EditProfilePage(player).setVisible(true);
    }//GEN-LAST:event_btnEditProfileActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        close();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        close();
        new ReportPage(player).setVisible(true);

    }//GEN-LAST:event_btnReportActionPerformed

    private void btnLeaderboardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaderboardsActionPerformed
        close();
        new LeaderBoard(player).setVisible(true);
    }//GEN-LAST:event_btnLeaderboardsActionPerformed

    private void btnSellTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellTokensActionPerformed
        close();
        new SellMenu(player).setVisible(true);
    }//GEN-LAST:event_btnSellTokensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen(new Player("1234", 12, 100, 10, 5, "5210799", "DemonX", 2000, 2, "Mubashir Ali", "mubashiralikalhoro@gmail.com")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyTokens;
    private javax.swing.JButton btnDoubleOrNothing;
    private javax.swing.JButton btnEditProfile;
    private javax.swing.JButton btnLeaderboards;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnRockPaperSessior;
    private javax.swing.JButton btnSellTokens;
    private javax.swing.JButton btnSlotMachine;
    private javax.swing.JButton btnTicTacToe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textAvatar;
    private javax.swing.JLabel textBuyTokens;
    private javax.swing.JLabel textBuyTokens1;
    private javax.swing.JLabel textBuyTokens2;
    private javax.swing.JLabel textEditProfile;
    private javax.swing.JLabel textEditProfile1;
    private javax.swing.JLabel textLevel;
    private javax.swing.JLabel textLogOut;
    private javax.swing.JLabel textPlayerId;
    private javax.swing.JLabel textScore;
    private javax.swing.JLabel textTokens;
    private javax.swing.JLabel textTotalWins;
    private javax.swing.JLabel textUserName;
    // End of variables declaration//GEN-END:variables
}
