/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.MainPages;

import BackEnd.DBConnection;
import BackEnd.ImageResizer;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hume
 */
public class SignUpForm extends javax.swing.JFrame {

    public SignUpForm() {
        initComponents();
        editTextPassword.setEchoChar((char) 0);
        editTextConfirmPassword.setEchoChar((char) 0);
        textEye.setIcon(ImageResizer.resize(new ImageIcon("C:\\Users\\Mubashir Ali\\Documents\\NetBeansProjects\\ArcadeGamingZone\\src\\GUI\\Images\\eyeIcon.png"), textEye));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        textEye = new javax.swing.JLabel();
        editTextLastName = new javax.swing.JTextField();
        editTextInGameName = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        editTextEmail = new javax.swing.JTextField();
        editTextConfirmPassword = new javax.swing.JPasswordField();
        editTextPassword = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JToggleButton();
        editTextFirstName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 0, 255));
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 110, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/TicTacToeButtonBack.png"))); // NOI18N
        jButton1.setBorder(null);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 40, 40));

        textEye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textEyeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                textEyeMouseReleased(evt);
            }
        });
        jPanel2.add(textEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 30, 30));

        editTextLastName.setBackground(new java.awt.Color(0, 0, 0));
        editTextLastName.setForeground(new java.awt.Color(255, 255, 255));
        editTextLastName.setText("Last Name");
        editTextLastName.setBorder(null);
        editTextLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editTextLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editTextLastNameFocusLost(evt);
            }
        });
        editTextLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextLastNameActionPerformed(evt);
            }
        });
        jPanel2.add(editTextLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 190, 31));

        editTextInGameName.setBackground(new java.awt.Color(0, 0, 0));
        editTextInGameName.setForeground(new java.awt.Color(255, 255, 255));
        editTextInGameName.setText("InGame Name");
        editTextInGameName.setBorder(null);
        editTextInGameName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editTextInGameNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editTextInGameNameFocusLost(evt);
            }
        });
        editTextInGameName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextInGameNameActionPerformed(evt);
            }
        });
        jPanel2.add(editTextInGameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 368, 31));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 368, 10));

        editTextEmail.setBackground(new java.awt.Color(0, 0, 0));
        editTextEmail.setForeground(new java.awt.Color(255, 255, 255));
        editTextEmail.setText("Enter your email address");
        editTextEmail.setBorder(null);
        editTextEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editTextEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editTextEmailFocusLost(evt);
            }
        });
        editTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextEmailActionPerformed(evt);
            }
        });
        jPanel2.add(editTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 368, 31));

        editTextConfirmPassword.setBackground(new java.awt.Color(0, 0, 0));
        editTextConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        editTextConfirmPassword.setText("Confirm your password");
        editTextConfirmPassword.setBorder(null);
        editTextConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editTextConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editTextConfirmPasswordFocusLost(evt);
            }
        });
        jPanel2.add(editTextConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 368, 31));

        editTextPassword.setBackground(new java.awt.Color(0, 0, 0));
        editTextPassword.setForeground(new java.awt.Color(255, 255, 255));
        editTextPassword.setText("Create a password");
        editTextPassword.setBorder(null);
        editTextPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editTextPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editTextPasswordFocusLost(evt);
            }
        });
        editTextPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(editTextPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 330, 31));

        btnSignUp.setBackground(new java.awt.Color(102, 102, 102));
        btnSignUp.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 0, 255));
        btnSignUp.setText("Submit");
        btnSignUp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel2.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 110, 50));

        editTextFirstName.setBackground(new java.awt.Color(0, 0, 0));
        editTextFirstName.setForeground(new java.awt.Color(255, 255, 255));
        editTextFirstName.setText("First Name");
        editTextFirstName.setBorder(null);
        editTextFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editTextFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editTextFirstNameFocusLost(evt);
            }
        });
        editTextFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextFirstNameActionPerformed(evt);
            }
        });
        jPanel2.add(editTextFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 170, 31));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 368, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 160, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 190, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 368, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 368, 10));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Copyright @2022 All Rights Reserved");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/loginpallate.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void editTextLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTextLastNameActionPerformed

    private void editTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTextEmailActionPerformed
    private void close() {
        WindowEvent windowClose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClose);

    }
    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        String username;
        String password;
        String email;
        String InGameName;
        if (!editTextFirstName.getText().equals("First Name")
                && !editTextLastName.getText().equals("Last Name")
                && !editTextEmail.getText().equals("Enter your email address")
                && !editTextPassword.getText().equals("Create a password")
                && !editTextConfirmPassword.getText().equals("Confirm your password")
                && !editTextInGameName.getText().equals("InGame Name")) {
            if (editTextPassword.getText().equals(editTextConfirmPassword.getText())) {
                if (new DBConnection().checkEmail(editTextEmail.getText())) {
                    username = editTextFirstName.getText() + " " + editTextLastName.getText();
                    password = editTextPassword.getText();
                    email = editTextEmail.getText();
                    InGameName = editTextInGameName.getText();
                    DBConnection dBC = new DBConnection();
                    dBC.addUser(username, password, email, InGameName);
                    close();
                    new LoginForm().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "email Already exists!\nPlease enter another email");

                }
            } else {
                JOptionPane.showMessageDialog(null, "please check your password!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
        }

    }//GEN-LAST:event_btnSignUpActionPerformed

    private void editTextFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTextFirstNameActionPerformed

    private void editTextFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editTextFirstNameFocusGained
        if (editTextFirstName.getText().equals("First Name")) {
            editTextFirstName.setText(null);
        }
    }//GEN-LAST:event_editTextFirstNameFocusGained

    private void editTextFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editTextFirstNameFocusLost
        if (editTextFirstName.getText().isEmpty()) {
            editTextFirstName.setText("First Name");
        }
    }//GEN-LAST:event_editTextFirstNameFocusLost

    private void editTextPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editTextPasswordFocusGained
        if (editTextPassword.getText().equals("Create a password")) {
            editTextPassword.setText(null);
            editTextPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_editTextPasswordFocusGained

    private void editTextPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editTextPasswordFocusLost
        if (editTextPassword.getText().isEmpty()) {
            editTextPassword.setText("Create a password");
            editTextPassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_editTextPasswordFocusLost

    private void editTextLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editTextLastNameFocusGained
        if (editTextLastName.getText().equals("Last Name")) {
            editTextLastName.setText(null);
        }
    }//GEN-LAST:event_editTextLastNameFocusGained

    private void editTextLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editTextLastNameFocusLost
        if (editTextLastName.getText().isEmpty()) {
            editTextLastName.setText("Last Name");
        }
    }//GEN-LAST:event_editTextLastNameFocusLost

    private void editTextEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editTextEmailFocusGained
        if (editTextEmail.getText().equals("Enter your email address")) {
            editTextEmail.setText(null);
        }
    }//GEN-LAST:event_editTextEmailFocusGained

    private void editTextEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editTextEmailFocusLost
        if (editTextEmail.getText().isEmpty()) {
            editTextEmail.setText("Enter your email address");
        }
    }//GEN-LAST:event_editTextEmailFocusLost

    private void editTextPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTextPasswordActionPerformed

    private void editTextConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editTextConfirmPasswordFocusGained
        if (editTextConfirmPassword.getText().equals("Confirm your password")) {
            editTextConfirmPassword.setText(null);
            editTextConfirmPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_editTextConfirmPasswordFocusGained

    private void editTextConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editTextConfirmPasswordFocusLost
        if (editTextConfirmPassword.getText().isEmpty()) {
            editTextConfirmPassword.setText("Confirm your password");
            editTextConfirmPassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_editTextConfirmPasswordFocusLost

    private void editTextInGameNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editTextInGameNameFocusGained
        if (editTextInGameName.getText().equals("InGame Name")) {
            editTextInGameName.setText(null);
        }
    }//GEN-LAST:event_editTextInGameNameFocusGained

    private void editTextInGameNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editTextInGameNameFocusLost
        if (editTextInGameName.getText().isEmpty()) {
            editTextInGameName.setText("InGame Name");
        }
    }//GEN-LAST:event_editTextInGameNameFocusLost

    private void editTextInGameNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextInGameNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTextInGameNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        close();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void textEyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEyeMousePressed
        editTextPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_textEyeMousePressed

    private void textEyeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEyeMouseReleased
       if(!editTextPassword.getText().equals("Create a password"))
        editTextPassword.setEchoChar('*');
    }//GEN-LAST:event_textEyeMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JToggleButton btnSignUp;
    private javax.swing.JPasswordField editTextConfirmPassword;
    private javax.swing.JTextField editTextEmail;
    private javax.swing.JTextField editTextFirstName;
    private javax.swing.JTextField editTextInGameName;
    private javax.swing.JTextField editTextLastName;
    private javax.swing.JPasswordField editTextPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel textEye;
    // End of variables declaration//GEN-END:variables
}
